# ********RoostGPT********

# Test generated by RoostGPT for test karateTest22March using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /laureate/{laureateID}_get for http method type GET 
# RoostTestHash=100d61e03c
# 
# 

# ********RoostGPT********
Feature: Laureate API

Background:
  * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
  * url urlBase

Scenario Outline: Test GET /2.1/laureate/{laureateID} endpoint
  Given path '2.1/laureate/', '<laureateID>'
  When method get
  Then match responseStatus == <statusCode>
  And match response == <responseBody>

Examples:
  | laureateID | statusCode | responseBody              |
  | '1'        | 200        | {}                        |
  | '999'      | 404        | { "code": "string", "message": "string" } |
  | 'abc'      | 400        | { "code": "string", "message": "string" } |
  | '-1'       | 422        | { "code": "string", "message": "string" } |
