# ********RoostGPT********

# Test generated by RoostGPT for test karateTest22March using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /laureates_get for http method type GET 
# RoostTestHash=41cb7e02aa
# 
# 

# ********RoostGPT********
Feature: Laureates API Testing

Background: 
  * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
  * url urlBase

Scenario Outline: Verify the Get Laureates API with different parameters
  Given path '/2.1/laureates'
  And param offset = <offset>
  And param limit = <limit>
  And param sort = <sort>
  And param ID = <ID>
  And param name = <name>
  And param gender = <gender>
  And param motivation = <motivation>
  And param affiliation = <affiliation>
  And param residence = <residence>
  And param birthDate = <birthDate>
  And param birthDateTo = <birthDateTo>
  And param deathDate = <deathDate>
  And param deathDateTo = <deathDateTo>
  And param foundedDate = <foundedDate>
  And param birthCity = <birthCity>
  And param birthCountry = <birthCountry>
  And param birthContinent = <birthContinent>
  And param deathCity = <deathCity>
  And param deathCountry = <deathCountry>
  And param deathContinent = <deathContinent>
  And param foundedCity = <foundedCity>
  And param foundedCountry = <foundedCountry>
  And param foundedContinent = <foundedContinent>
  And param HeadquartersCity = <HeadquartersCity>
  And param HeadquartersCountry = <HeadquartersCountry>
  And param HeadquartersContinent = <HeadquartersContinent>
  And param nobelPrizeYear = <nobelPrizeYear>
  And param yearTo = <yearTo>
  And param nobelPrizeCategory = <nobelPrizeCategory>
  And param format = <format>
  And param csvLang = <csvLang>
  When method get
  Then status 200
  And match response contains {laureates: '#array'}

Examples:
  | offset | limit | sort | ID | name | gender | motivation | affiliation | residence | birthDate | birthDateTo | deathDate | deathDateTo | foundedDate | birthCity | birthCountry | birthContinent | deathCity | deathCountry | deathContinent | foundedCity | foundedCountry | foundedContinent | HeadquartersCity | HeadquartersCountry | HeadquartersContinent | nobelPrizeYear | yearTo | nobelPrizeCategory | format | csvLang |
  | 1      | 1     | 'asc' | 1  | 'test' | 'male' | 'test motivation' | 'test affiliation' | 'test residence' | '2000-01-01' | '2001-01-01' | '2002-01-01' | '2003-01-01' | '2004-01-01' | 'test birthCity' | 'test birthCountry' | 'test birthContinent' | 'test deathCity' | 'test deathCountry' | 'test deathContinent' | 'test foundedCity' | 'test foundedCountry' | 'test foundedContinent' | 'test HeadquartersCity' | 'test HeadquartersCountry' | 'test HeadquartersContinent' | 2000 | 2001 | 'test nobelPrizeCategory' | 'test format' | 'test csvLang' |

