# ********RoostGPT********

# Test generated by RoostGPT for test karateTest22March using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /nobelPrizes_get for http method type GET 
# RoostTestHash=977dd819cb
# 
# 

# ********RoostGPT********
Feature: Nobel Prizes API Test

Background:
  * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
  * url urlBase

Scenario Outline: Verify successful retrieval of Nobel Prizes
  Given path '/2.1/nobelPrizes'
  And params { offset: '<offset>', limit: '<limit>', sort: '<sort>', nobelPrizeYear: '<nobelPrizeYear>', yearTo: '<yearTo>', nobelPrizeCategory: '<nobelPrizeCategory>', format: '<format>', csvLang: '<csvLang>' }
  When method get
  Then status 200
  And match response contains { nobelPrizes: '#array', meta: '#object', links: '#array' }
  And match each response.nobelPrizes[*].awardYear == '#number'
  And match each response.nobelPrizes[*].prizeAmount == '#number'
  And match response.meta.offset == '<offset>'
  And match response.meta.limit == '<limit>'

Examples:
  | offset | limit | sort  | nobelPrizeYear | yearTo | nobelPrizeCategory | format | csvLang |
  | 1      | 10    | 'asc' | 2000           | 2020   | 'eco'              | 'json' | 'en'    |

Scenario Outline: Verify error handling for Nobel Prizes retrieval
  Given path '/2.1/nobelPrizes'
  And params { offset: '<offset>', limit: '<limit>', sort: '<sort>', nobelPrizeYear: '<nobelPrizeYear>', yearTo: '<yearTo>', nobelPrizeCategory: '<nobelPrizeCategory>', format: '<format>', csvLang: '<csvLang>' }
  When method get
  Then status <statusCode>
  And match response contains { code: '#string', message: '#string' }

Examples:
  | offset | limit | sort  | nobelPrizeYear | yearTo | nobelPrizeCategory | format | csvLang | statusCode |
  | 0      | 10    | 'asc' | 2000           | 2020   | 'eco'              | 'json' | 'en'    | 400        |
  | 1      | 10    | 'asc' | 1890           | 2020   | 'eco'              | 'json' | 'en'    | 422        |
  | 1      | 10    | 'asc' | 2000           | 2020   | 'unknown'          | 'json' | 'en'    | 404        |
