# ********RoostGPT********

# Test generated by RoostGPT for test karateTest22March using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /nobelPrize/{category}/{year}_get for http method type GET 
# RoostTestHash=9818bf6b39
# 
# 

# ********RoostGPT********
Feature: Nobel Prize API

Background:
  * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
  * url urlBase

Scenario Outline: Obtain information about one specific Nobel Prize
  Given path '2.1/nobelPrize', '<category>', '<year>'
  When method get
  Then status <status>

  * def responseHeaders = responseHeaders
  * match responseHeaders contains { 'Content-Type': '#string' }

  * def responseBody = response
  * match responseBody == { nobelPrize: '#object' }

  * match responseBody.nobelPrize contains 
    {
      awardYear: '#number',
      category: '#object',
      categoryFullName: '#object',
      dateAwarded: '#string',
      prizeAmount: '#number',
      prizeAmountAdjusted: '#number',
      topMotivation: '#object',
      laureates: '#array'
    }

  Examples:
    | category | year | status |
    | 'physics' | 2020 | 200   |
    | 'chemistry' | 2019 | 200 |
    | 'medicine' | 2018 | 200 |
    | 'literature' | 2017 | 200 |
    | 'peace' | 2016 | 200 |
    | 'economics' | 2015 | 200 |
